version: '3.8'
services:
  app:
    container_name: experiments_service
    build: .
    env_file:
      - .env
    ports: 
      - 8080:8080 
    volumes:
      - .:/usr/src/app/
    depends_on:
      - fullstack-postgres   
    command: go run cmd/service_api/main.go 

  fullstack-postgres:
    image: postgres:latest
    container_name: full_db_postgres
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_USERPASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data

volumes:
  database_postgres:                  
